name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Скачиваем код из репозитория
      uses: actions/checkout@v4
    
    - name: Устанавливаем Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Запускаем тесты
      run: |
        python -m unittest test_palindrome.py
